// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:in_out/servicies/keys.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: Keys.firebaseAPiKeyWeb,
    appId: '1:${Keys.firebaseMessagingSenderId}:web:695b18ae3ad9244783eb12',
    messagingSenderId: Keys.firebaseMessagingSenderId,
    projectId: Keys.firebaseProjectId,
    authDomain: Keys.firebaseStorageBucket,
    storageBucket: Keys.firebaseStorageBucket,
    measurementId: 'G-EH2TCK97VY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: Keys.firebaseApiKeyAndroid,
    appId: '1:${Keys.firebaseMessagingSenderId}:android:285cb773d6d2f7ee83eb12',
    messagingSenderId: Keys.firebaseMessagingSenderId,
    projectId: Keys.firebaseProjectId,
    storageBucket: Keys.firebaseStorageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: Keys.firebaseAPiKeyIos,
    appId: '1:${Keys.firebaseMessagingSenderId}:ios:6a278b9779b7a58383eb12',
    messagingSenderId: Keys.firebaseMessagingSenderId,
    projectId: Keys.firebaseProjectId,
    storageBucket: Keys.firebaseStorageBucket,
    androidClientId:
        '${Keys.firebaseMessagingSenderId}-e0acv9ffvr1c5d6q3r5cn1tj4tsqq8sd.apps.googleusercontent.com',
    iosBundleId: 'com.finances.inOut',
  );
}
